### ISSUE TITLE
Running on MacOS

### ISSUE THREAD

**Issue by PCswanson** [EiichiroIto/NovaStelo#1]
Hello! I used StarLogo with my students to create biological simulations years ago and would like to again, but most of my students have macs and the software doesn't work on current computers. I downoloaded Pharo for Mac and your files, but I am lost as to how to get it working (as well as how to save a runtime for Mac if possible). I'm happy to do the work if you could give me any suggestions on how to start

Thanks,

**Comment by EiichiroIto** [comment]
Thank you for your interest and comment. I uploaded new release files including mac binaries. Would you like to check this files?

**Comment by PCswanson** [comment]
Thank you for doing this! Unfortunatly, when I download and unzip I get the following message: 

> “NovaStelo-v1.2.0-mac” is damaged and can’t be opened. You should move it to the Trash.

Possibly it got damaged when it was zipped or uploaded? Could you try again when you have a chance?

Thanks!

**Comment by EiichiroIto** [comment]
The message "app is damaged and can't be opened..." is from GateKeeper on Mac for security. I don't have apple's developers id and I can't sign my application.
There are some workarounds for starting unsigned applications. see Installation section of https://pharo.org/download.

Or the way it worked out is:
- unarchive the zipped file.
- start Terminal app then enter this: "cd Downloads"
- then enter: "xattr -cr NovaStelo-v1.2.0-mac.app"
After this, the app will start normally.

**Comment by PCswanson** [comment]
Thank you!
